services:
  - type: web
    name: sdown-app
    env: python
    pythonVersion: 3.10.12 
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn sdown1:app --bind 0.0.0.0:$PORT

